ALTER TABLE users
ADD COLUMN name VARCHAR(255) NOT NULL,
ADD COLUMN verified_email BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN given_name VARCHAR(255) NOT NULL,
ADD COLUMN family_name VARCHAR(255) NOT NULL,
ADD COLUMN picture TEXT NOT NULL,
ADD COLUMN locale VARCHAR(10) NOT NULL;
