coverage:
  status:
    project:
      default:
        target: 0
        threshold: 0%
        base: auto
        if_ci_failed: error
        informational: true
        only_pulls: false
    patch:
      default:
        target: 0
        threshold: 0%
        base: auto
        if_ci_failed: error
        only_pulls: false
