CREATE TABLE "account_query" (
  "view_id" TEXT PRIMARY KEY NOT NULL,
  "version" BIGINT NOT NULL,
  "payload" JSON NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);