// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "bank_account_service.proto" (package "bank_account_service", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BankAccountService } from "./bank_account_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetBankAccountResponse } from "./bank_account_service";
import type { GetBankAccountRequest } from "./bank_account_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Service definition
 *
 * @generated from protobuf service bank_account_service.BankAccountService
 */
export interface IBankAccountServiceClient {
    /**
     * @generated from protobuf rpc: GetBankAccount(bank_account_service.GetBankAccountRequest) returns (bank_account_service.GetBankAccountResponse);
     */
    getBankAccount(input: GetBankAccountRequest, options?: RpcOptions): UnaryCall<GetBankAccountRequest, GetBankAccountResponse>;
}
/**
 * Service definition
 *
 * @generated from protobuf service bank_account_service.BankAccountService
 */
export class BankAccountServiceClient implements IBankAccountServiceClient, ServiceInfo {
    typeName = BankAccountService.typeName;
    methods = BankAccountService.methods;
    options = BankAccountService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetBankAccount(bank_account_service.GetBankAccountRequest) returns (bank_account_service.GetBankAccountResponse);
     */
    getBankAccount(input: GetBankAccountRequest, options?: RpcOptions): UnaryCall<GetBankAccountRequest, GetBankAccountResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBankAccountRequest, GetBankAccountResponse>("unary", this._transport, method, opt, input);
    }
}
