name: "veloxide-backend-cd"

on:
  push:
    branches:
      - main
      - liamwh/sveltekit-frontend

jobs:
  deploy:
    name: Deploy Veloxide Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp -r ./contracts/ ./backend/contracts
      - run: cp -r ./contracts/ ./backend/crates/veloxide-server
      - run: ls -R .
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./backend
        env:
          CONTRACTS_PATH: ./contracts
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
